version: "3"

services:

  edge:
    image: svnedge/devbuild:latest
    ports:
      - "18080:18080"
      - "3343:3343"
    environment:
      SET_PERMS: "false"
    volumes:
      - ./data:/home/svnedge/csvn/data

  ldap:
    container_name: demo-ldap
    hostname: ldap
    environment:
      LDAP_TLS_VERIFY_CLIENT: "try"
    build:
      context: ldap
      dockerfile: Dockerfile
    ports:
      - "1389:389"
      - "1636:636"
